@startuml diagramaCasosDeUso

actor Administrador
actor Usuario

usecase "Iniciar Sesión" as UC1
usecase "Ver Métricas de Servicios" as UC2
usecase "Ver Logs de Servicios" as UC3
usecase "Configurar Alertas" as UC4
usecase "Personalizar Dashboard" as UC5
usecase "Crear Usuario" as UC6
usecase "Asignar Roles" as UC7
usecase "Eliminar Usuario" as UC8
usecase "Actualizar Usuario" as UC9

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC4
Usuario --> UC5
Administrador --> UC6
Administrador --> UC7
Administrador --> UC8
Administrador --> UC9

@enduml
